// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers/query-provider";
import { PageProvider } from "../context/PageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <PageProvider>{children}</PageProvider>
        </Providers>
      </body>
    </html>
  );
}
